//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PQS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUOTE
    {
        public short ID { get; set; }
        public short IDUSER { get; set; }
        public string CODE { get; set; }
        public Nullable<short> IDATTACHMENT { get; set; }
        public string NAME { get; set; }
        public string CAPTION { get; set; }
    
        public virtual ATTACHMENT ATTACHMENT { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual TYPEQUOTE TYPEQUOTE { get; set; }
    }
}
